# Generated by Django 5.1.7 on 2025-03-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userproductsbought'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductrelation',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 'Bad'), (2, 'Nice'), (3, 'Good'), (4, 'Amazing'), (5, 'Insane')], null=True),
        ),
    ]
