# Generated by Django 5.1.7 on 2025-03-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(choices=[('currency', 'Внутриигровая валюта'), ('item', 'Игровой предмет'), ('account', 'Игровой аккаунт'), ('service', 'Услуга'), ('other', 'Другое')], max_length=15, verbose_name='Категория')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('sold', 'Проданный'), ('deleted', 'Удаленный')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обнавления')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
            ],
        ),
    ]
